cc_library(
    name="hdfs3",
    srcs=[
        "libhdfs3/client/*.cpp",
        "libhdfs3/common/*.cpp",
        "libhdfs3/network/*.cpp",
        "libhdfs3/rpc/*.cpp",
        "libhdfs3/server/*.cpp",
        "libhdfs3/proto/generated/*.cc",
    ],
    incs=[
        "libhdfs3/client",
        "libhdfs3/common",
        "libhdfs3/network",
        "libhdfs3/rpc",
        "libhdfs3/server",
        "libhdfs3/proto/generated",
        "libhdfs3",
    ],
    export_incs=[
        ".",
        #"src/proto/generated",
    ],
    deps=[
        "#pthread",
        "#dl",
        "cpp3rdlib/gtest:1.6.0@//cpp3rdlib/gtest:gtest",
        "cpp3rdlib/googlemock:1.8.0@//cpp3rdlib/googlemock:gmock",
        "cpp3rdlib/protobuf:2.5.0@//cpp3rdlib/protobuf:protobuf",
        "cpp3rdlib/openssl:1.0.1@//cpp3rdlib/openssl:ssl,crypto",
        "cpp3rdlib/unwind:1.1-3.2@//cpp3rdlib/unwind:unwind,unwind-coredump,unwind-generic,unwind-ptrace",
        "cpp3rdlib/curl:7.46.0@//cpp3rdlib/curl:curl",
        "cpp3rdlib/gsasl:v1.8.0@//cpp3rdlib/gsasl:gsasl",
        "cpp3rdlib/libxml2:v2.9.2@//cpp3rdlib/libxml2:xml2",
        "cpp3rdlib/krb5:1.15@//cpp3rdlib/krb5:gssrpc,k5crypto,kadm5clnt,kadm5srv,kdb5,krb5,krb5support",
        "cpp3rdlib/uuid:2.29.2@//cpp3rdlib/uuid:uuid",
        "cpp3rdlib/boost:1.56.0@//cpp3rdlib/boost:boost,boost_atomic,boost_chrono,boost_thread",
        "cpputil/infsec:1.3.0@//cpputil/infsec:infsec",
        #":libhdfs3_proto"
    ],
    extra_cppflags=["-Wextra -Wno-unused-local-typedefs -std=c++14 -Werror -g -msse4 -Wno-error=extra"],
    extra_linkflags=["-Wl,-soname,libhdfs3.so"],
    build_dynamic=True
)

'''
proto_library(
    name="libhdfs3_proto",
    srcs=["src/proto/*.proto"],
    incs=["src/proto"]
)
'''

